### ISSUE TITLE
Reset Function

### ISSUE THREAD

**Issue by calperxd** [fhnw-ise-qcrypt/mcp3564#10]
Hi, I was trying to convert your code to my current code base and I'm was facing one issue related to the reset command.

Are you sure that `0b01111010` send the reset command ?

As you can see in datasheet p. 68([here](https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP3561_2_4R-Data-Sheet-DS200006391C.pdf)) says that to reset we must send  `0b01111000` instead of `0b01111010`, please if I'm wrong let me know 
![image](https://github.com/fhnw-ise-qcrypt/mcp3564/assets/48101913/234f32c0-8fe6-4fa8-b799-80ae8bbfdbe2)

**Comment by mnemocron** [comment]
This indeed appears to be correct. Thanks for reporting.

**Comment by paul-thelu** [comment]
Hi there, let me know if I'm wrong @mnemocron  but I think your code was correct prior to modifying it (before commit 786cb6a)

The fast command to be sent for a RESET, when device address is 0x01, must be 0b0111 1000 which was the case before.
The current version sends only 0b0011 1000 (equivalent to 0xE << 2) and does not take into account the device address bits position [7:6] whose value is 0x01.

@calperxd Could you confirm this?

Also a few useful fast commands can be added at the bottom of mcp356xr.h:
#define DEVICE_ADC_START_RESTART_COMMAND 	(0xA << _MCP3561_COMMAND_ADDR_POS) | MCP3561_FAST_COMMAND
#define DEVICE_ADC_STANDBY_COMMAND 			(0xB << _MCP3561_COMMAND_ADDR_POS) | MCP3561_FAST_COMMAND
#define DEVICE_ADC_SHUTDOWN_COMMAND 		(0xC << _MCP3561_COMMAND_ADDR_POS) | MCP3561_FAST_COMMAND
#define DEVICE_ADC_FULL_SHUTDOWN_COMMAND 	(0xD << _MCP3561_COMMAND_ADDR_POS) | MCP3561_FAST_COMMAND

**Comment by calperxd** [comment]
Hi @paul-thelu  I took a look in the header file and you're right the device addr is missing.


The current value is :
`#define DEVICE_RESET_COMMAND                (0xE << _MCP3561_COMMAND_ADDR_POS) | MCP3561_FAST_COMMAND`


The right value should be 

`#define DEVICE_RESET_COMMAND               (MCP3561_DEVICE_ADDRESS_MASK) | (0xE << _MCP3561_COMMAND_ADDR_POS) | MCP3561_FAST_COMMAND`


Could you take a look @mnemocron ?

**Comment by paul-thelu** [comment]
@calperxd Did you think of checking out the changes from yesterday?

I don't think your changes are working/useful since MCP3561_FAST_COMMAND already embeds the Device ID address.

NB: Current version RESET cmd is tested and working on my setup along with all the other fast commands that have been added yesterday.

**Comment by calperxd** [comment]
I'm sorry for that I didn't see, my bad.

But in this case even if I'm write it wrong, I'm just doing the bit wise operation twice. Thanks for your observation.
