### ISSUE TITLE
MCP3561_Reset() might be incorrect.

### ISSUE THREAD

**Issue by wdlut** [fhnw-ise-qcrypt/mcp3564#11]
src/mcp3564.c:158 
When I compile the code, my compiler tells me, that _MCP3561_write() is called with a value instead of a pointer ant I think, he is right. 
Current code:
```
void MCP3561_Reset(SPI_HandleTypeDef *hspi){
	uint8_t cmd;
	cmd = DEVICE_RESET_COMMAND;
	_MCP3561_write(hspi, cmd, 1);
}
```
My code: 
```
void MCP3561_Reset(SPI_HandleTypeDef *hspi){
	uint8_t cmd;
	cmd = DEVICE_RESET_COMMAND;
	_MCP3561_write(hspi, &cmd, 1);
}
```
There is also a missing / in a comment in inc/mcp3564.h:262, which was introduced in the last check-in.

**Comment by mnemocron** [comment]
That observation is correct. Thanks for reporting :D
