### ISSUE TITLE
an extra tDLY in the excel

### ISSUE THREAD

**Issue by LeiShifu** [fhnw-ise-qcrypt/mcp3564#4]
as the datasheet said "The delay is only added in between two conversions of the same scan cycle. There is no delay added at the end or the beginning of each scan cycle due to the DLY[2:0] settings."(Page55)
the right scan timing should be this:
![DQBKXOD}6 )QV{1`C6M_~CI](https://user-images.githubusercontent.com/18900207/201823288-069121d0-aae8-49e8-9031-cbcb546e2e21.png)

testing with oscilloscope： converting 3 channels，AMCLK=18.66Mhz，OSR=1024，DLY[2:0]=111(512DMCLK)，TIMER[23:0]=0x000000，CH1 connect to the MCLK pin and CH3 connect to the IRQ pin
![AMCLK=18 6666Mhz，OSR=1024，](https://user-images.githubusercontent.com/18900207/201824870-495634ab-8c07-47b0-9335-02c0d314d02d.png)

definition of MCP3561_CONFIG1_OSR_8192 in mcp3564.h should be 0x08 instead of 0x09

**Comment by mnemocron** [comment]
Thank you for pointing that out. I will have a look at it.

Also, are you sure about this one?

> definition of MCP3561_CONFIG1_OSR_8192 in mcp3564.h should be 0x08 instead of 0x09

It looks correct in the current version:
https://github.com/fhnw-ise-qcrypt/mcp3564/blob/main/inc/mcp3564.h#L99

**Comment by mnemocron** [comment]
yup, you were right, thanks again 👍
