### ISSUE TITLE
OFFSET CAL register not working

### ISSUE THREAD

**Issue by paul-thelu** [fhnw-ise-qcrypt/mcp3564#7]
Hi there,
First off thank you for the useful library.
Just found an issue which prevent the user from using OFFSET CAL register.

Turns out the issue was a typo in [mcp3564.h](https://github.com/fhnw-ise-qcrypt/mcp3564/blob/main/inc/mcp3564.h) lines 232 to 234:
- "MCP3561_TIMER_ADDR" should be replaced by "MCP3561_OFFSETCAL_ADDR"

**Comment by mnemocron** [comment]
That was a good catch, thank you :)
