### ISSUE TITLE
SPI CS not asserted prior to transmitting SPI

### ISSUE THREAD

**Issue by paul-thelu** [fhnw-ise-qcrypt/mcp3564#8]
Hi Simon,

Sorry to reach out again, but there's no CS Low/High sequence before and after HAL_SPI_Transmit [here](https://github.com/fhnw-ise-qcrypt/mcp3564/blob/8e8f7346c8eaa48aad27445d73994b657d7a4b01/src/mcp3564.c#L160C2-L160C18)

Hence the RESET fast command is not sent properly.

Maybe could be a nice idea to replace it with that low level SPI function written at the top of the file 
"void _MCP3561_write(SPI_HandleTypeDef *hspi, uint8_t *pData, uint16_t size);"

Have a great day :)

**Comment by mnemocron** [comment]
Hi, thanks for pointing that out. I never used the reset function, so it slipped through.
